"""Write the recipes whose groups changed when cluster started matching on ingredients.

Seven groups used to join different recipes that share a title (two "Pastel navideño", two
"Spritz", ...). Each side now gets its own recipe, written from cache/pages/ only.
"""

import json
from pathlib import Path

RECIPES = Path("cache/recipes")

FIXES = {
    "7#1": {
        "refs": ["7#1", "8#1", "11#1", "17#1"],
        "title": "Pastel navideño",
        "category": "Postres y pasteles",
        "tags": ["horneado", "festivo", "frutas"],
        "servings": "",
        "prep_time": "",
        "cook_time": "40 a 50 min",
        "temperature": "350 °F",
        "ingredient_groups": [
            {"name": "Masa", "items": [
                "1/2 libra de mantequilla sin sal",
                "1 taza de azúcar glass",
                "1/2 cucharadita de vainilla",
                "1/2 cucharadita de esencia de almendra",
                "1/2 cucharadita de sal",
                "1 cucharadita de ralladura de naranja",
                "5 huevos, separadas las claras de las yemas",
            ]},
            {"name": "Secos (cernidos juntos)", "items": [
                "2 tazas de harina cernida",
                "1 cucharadita de bicarbonato (solo en la copia de INTECAP)",
                "1/4 cucharadita de pimienta (una pizca en la copia de INTECAP)",
                "1/4 cucharadita de nuez moscada",
                "1/4 cucharadita de clavo",
                "1/4 cucharadita de jengibre",
                "1/2 cucharadita de canela",
            ]},
            {"name": "Líquido", "items": [
                "2 cucharaditas de café instantáneo",
                "1/2 taza de agua caliente",
                "3/4 taza de vino dulce",
            ]},
            {"name": "Frutas", "items": [
                "1/3 taza de harina para enharinar la fruta",
                "1/2 libra de pasas",
                "1/2 libra de fruta cristalizada",
                "1/2 libra de ciruelas sin semillas, picadas",
                "1/2 libra de nueces picadas",
                "4 onzas de almendras",
            ]},
        ],
        "steps": [
            "Cremar muy bien la mantequilla ablandada con el azúcar glass. Agregar las yemas una por una, la vainilla, la esencia de almendras y la ralladura de naranja.",
            "Aparte, disolver el café en el agua y añadir el vino.",
            "Agregar a la mezcla de mantequilla los ingredientes secos previamente cernidos, alternando con el líquido. Terminar con harina.",
            "Agregar la fruta enharinada y, al final, con movimiento envolvente, las claras batidas a punto de nieve.",
            "Verter la mezcla en moldes engrasados y enharinados.",
            "Hornear a 350 °F de 40 a 50 minutos, o hasta que al insertar un palillo este salga limpio.",
        ],
        "teacher_notes": [
            "En la copia de INTECAP la pimienta está tachada y corregida a mano: solo una pizca.",
        ],
        "notes": [
            "Se puede hacer con un mes de anticipación: se baña cada 8 días con una copita de vino dulce y se guarda envuelto en papel de aluminio a temperatura ambiente. Si es por más tiempo, se refrigera.",
            "INTECAP Formación a Distancia, instructora Sra. Emma de Rodríguez.",
        ],
    },
    "11#2": {
        "refs": ["11#2", "12#1"],
        "title": "Pastel navideño con ron",
        "category": "Postres y pasteles",
        "tags": ["horneado", "festivo", "frutas"],
        "servings": "",
        "prep_time": "",
        "cook_time": "30 a 40 min",
        "temperature": "",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "1 libra de mantequilla",
            "2 tazas de azúcar mascabado",
            "1 docena de huevos pequeños u 8 grandes",
            "3 tazas de harina cernida",
            "1 cucharadita de royal",
            "1 cucharadita de nuez moscada",
            "2 sobres de canela",
            "1 cucharadita de clavo en polvo",
            "1 taza de nuez picada",
            "1 taza de fruta cristalizada",
            "2 onzas de pasas",
            "2 o 3 copitas de ron (1/3 a 1/2 taza)",
        ]}],
        "steps": [
            "Batir muy bien la mantequilla y el azúcar hasta que quede cremosa.",
            "Añadir los huevos uno a uno sin dejar de batir.",
            "Agregar los ingredientes secos cernidos hasta que la masa esté bien consistente.",
            "Agregar las frutas enharinadas en forma envolvente.",
            "Poner en un molde engrasado y enharinado y hornear de 30 a 40 minutos.",
            "Cuando esté listo, envolverlo en papel encerado y mojarlo con ron todos los días hasta que se vaya a comer.",
        ],
        "teacher_notes": [],
        "notes": [
            "Se puede preparar de 8 a 15 días antes de comerlo (una copia dice de 15 a 30 días).",
            "La receta aparece dos veces: una copia pide 1/2 taza de ron y 35 a 40 minutos de horno; la otra 1/3 de taza y 30 a 40 minutos.",
        ],
    },
    "20#1": {
        "refs": ["20#1"],
        "title": "Chiffón de naranja",
        "category": "Postres y pasteles",
        "tags": ["horneado", "frutas"],
        "servings": "",
        "prep_time": "",
        "cook_time": "60 min aprox.",
        "temperature": "175 °C",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "2 tazas de harina",
            "1/2 taza de maicena",
            "1 1/4 taza de azúcar",
            "4 cucharaditas de polvo de hornear",
            "1/2 taza de aceite",
            "6 huevos",
            "2 1/2 cucharaditas de ralladura de naranja",
            "3/4 taza de jugo de naranja",
            "1/2 cucharadita de crémor tártaro",
            "1/2 cucharadita de sal",
        ]}],
        "steps": [
            "Separar las claras y las yemas.",
            "Cernir los ingredientes secos.",
            "Mezclar con batidora todos los ingredientes menos las claras y el crémor tártaro; debe quedar una masa pareja.",
            "Batir las claras con el crémor tártaro hasta que tengan espesor de merengue.",
            "Unir las dos preparaciones con movimiento envolvente.",
            "Poner en un molde engrasado y enharinado solo en el fondo.",
            "Hornear en horno precalentado a 175 °C por 60 minutos aproximadamente.",
            "Dejar enfriar 10 minutos en el molde y luego desmoldar.",
            "Decorar en frío con azúcar glass en forma de lluvia.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "215#1": {
        "refs": ["215#1"],
        "title": "Chiffón de naranja (masa esponjosa)",
        "category": "Postres y pasteles",
        "tags": ["horneado", "frutas"],
        "servings": "",
        "prep_time": "",
        "cook_time": "60 a 75 min",
        "temperature": "325 °F",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "2 tazas de harina",
            "1 1/2 tazas de azúcar",
            "3 cucharaditas de royal (polvo de hornear)",
            "1 cucharadita de sal",
            "1/2 taza de aceite",
            "7 yemas de huevo",
            "3/4 taza de agua fría",
            "2 cucharadas de ralladura de naranja",
            "1 taza de claras (7 u 8 claras)",
            "1/2 cucharadita de crémor tártaro",
        ]}],
        "steps": [
            "Precalentar el horno a 325 °F.",
            "Mezclar la harina, el azúcar, el royal y la sal. En el centro agregar el aceite, las yemas, el agua y la ralladura de naranja. Mezclar hasta que la masa esté pareja.",
            "Batir las claras con el crémor tártaro en un bol grande hasta que formen picos duros.",
            "Incorporar la mezcla de yemas a las claras con movimiento envolvente, solo hasta que se integren.",
            "Colocar en un molde de tubo de 10 por 4 pulgadas sin engrasar. Hornear de 60 a 75 minutos, o hasta que al tocarlo suavemente regrese.",
            "Invertir el molde de inmediato y dejar enfriar completamente colgado antes de desmoldar.",
        ],
        "teacher_notes": [],
        "notes": ["Instituto Femenino de Estudios Superiores, Hogar Empresa I, Repostería, Sra. Beatriz de Arzú."],
    },
    "84#1": {
        "refs": ["84#1"],
        "title": "Ensalada moldeada",
        "category": "Entradas y bocadillos",
        "tags": ["sin horno", "carne"],
        "servings": "",
        "prep_time": "30 min",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "6 a 7 tazas de papas cocidas frías, tajeadas (o coditos)",
            "1 a 1/2 taza de cebolla picada fina",
            "1/2 taza de apio picado fino",
            "1/2 taza de perejil picado fino",
            "Sal y pimienta al gusto",
            "6 rodajas de jamón picado fino",
            "1 1/2 taza de mayonesa con gotitas de limón y mostaza",
            "2 sobres de gelatina sin sabor disueltos en agua (1/2 a 3/4 taza de agua por sobre)",
            "6 a 8 rodajas de jamón para decorar",
            "Perejil colocho",
        ]}],
        "steps": [
            "En un bowl unir la mayonesa con el perejil, apio, cebolla y jamón picado, y sazonar con sal y pimienta.",
            "Incorporar las papas cocidas frías y revolver bien.",
            "Aparte, disolver la gelatina sin sabor en el agua a baño María y agregarla a la mezcla.",
            "Forrar un molde alargado con papel aluminio, colocar rodajas de jamón en el fondo y las paredes, y luego la mezcla de papas.",
            "Refrigerar por lo menos 3 horas para que cuaje.",
            "Desmoldar en un platón adornado con perejil colocho.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "201#1": {
        "refs": ["201#1"],
        "title": "Ensalada moldeada (Hogar Empresa II)",
        "category": "Entradas y bocadillos",
        "tags": ["sin horno", "carne"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "1 1/2 libra de papas tajeadas y cocidas (o coditos)",
            "1/2 taza de cebolla picada fina",
            "1 taza de apio picado fino",
            "1/4 taza de perejil picado fino",
            "1 cucharadita de sal",
            "1/4 cucharadita de pimienta",
            "1/2 libra de jamón cortado en cuadros pequeños",
            "1 1/2 taza de mayonesa con limón y mostaza al gusto",
            "2 sobres de gelatina sin sabor disuelta en 1/2 taza de agua fría y 1/2 taza de agua caliente",
            "Rodajas de jamón y perejil colocho para decorar",
        ]}],
        "steps": [
            "Mezclar todos los ingredientes excepto la gelatina.",
            "Agregar la gelatina disuelta en caliente.",
            "Colocar en un molde engrasado con mayonesa o aceite.",
            "Refrigerar por lo menos 3 horas.",
            "Desmoldar y decorar con rodajas de jamón y perejil colocho.",
        ],
        "teacher_notes": [],
        "notes": ["Instituto Femenino de Estudios Superiores, Hogar Empresa II, Arte Culinario, Margarita de Sánchez."],
    },
    "108#1": {
        "refs": ["108#1"],
        "title": "Spritz",
        "category": "Postres y pasteles",
        "tags": ["horneado"],
        "servings": "Aproximadamente 5 docenas de galletas",
        "prep_time": "20 min",
        "cook_time": "6 a 9 min",
        "temperature": "400 °F",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "1 taza de mantequilla o margarina",
            "1/2 taza de azúcar",
            "1 huevo",
            "1/2 cucharadita de sal",
            "1 cucharadita de esencia de almendra o vainilla",
            "2 1/4 tazas de harina",
        ]}],
        "steps": [
            "Precalentar el horno a 400 °F.",
            "Mezclar la mantequilla o margarina con el azúcar, el huevo, la sal y la esencia hasta que estén bien integrados.",
            "Agregar la harina y mezclar hasta obtener una masa uniforme.",
            "Tomando aproximadamente 1/4 de la masa a la vez, colocarla en la prensa para galletas con el disco deseado.",
            "Formar las galletas sobre una lata para hornear sin engrasar y fría.",
            "Hornear de 6 a 9 minutos.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "186#2": {
        "refs": ["186#2", "193#2"],
        "title": "Spritz de colores",
        "category": "Postres y pasteles",
        "tags": ["horneado", "festivo"],
        "servings": "",
        "prep_time": "",
        "cook_time": "10 a 12 min",
        "temperature": "350 °F",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "1 1/2 taza de mantequilla",
            "1 taza de azúcar",
            "1 huevo",
            "1 cucharadita de esencia de vainilla o almendra",
            "3 a 4 tazas de harina cernida",
            "1 cucharadita de royal",
            "Colorantes",
            "Guindas y fruta cristalizada",
        ]}],
        "steps": [
            "Batir la mantequilla y el azúcar.",
            "Agregar el huevo, la esencia y la harina junto con el royal.",
            "Si se desea, pintar la masa con colorantes. Formar las galletas en la máquina de tubo de galletas.",
            "Decorar con guindas y fruta cristalizada.",
            "Hornear a 350 °F por 10 a 12 minutos.",
        ],
        "teacher_notes": [],
        "notes": ["Hogar Empresa II, Arte Culinario, Margarita de Sánchez."],
    },
    "153#1": {
        "refs": ["153#1"],
        "title": "Enchiladas suizas",
        "category": "Platos principales",
        "tags": ["pollo", "horneado"],
        "servings": "25 enchiladas",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [
            {"name": "Relleno", "items": [
                "3 pechugas de pollo cocidas y desmenuzadas",
                "1 queso de capas (o queso Oaxaca o pita)",
                "25 tortillas de maíz frescas",
            ]},
            {"name": "Salsa verde", "items": [
                "1 a 1 1/2 libras de miltomate asado",
                "4 chiles pimiento verdes, asados y pelados",
                "1 manojo de cilantro (apartar un poco picado para decorar)",
                "Caldo de pollo",
                "Cebolla picada al gusto",
                "Grasa o aceite para freír",
                "Sal y una pizca de azúcar al gusto",
                "1 vaso de crema fresca",
            ]},
            {"name": "Para gratinar", "items": ["4 onzas de queso parmesano rallado"]},
        ],
        "steps": [
            "Asar los miltomates y los chiles pimientos. Pelar los chiles y licuarlos con los miltomates, un poco de cilantro y caldo de pollo.",
            "En una sartén con un poco de grasa freír la cebolla picada, verter la salsa licuada, sazonar con sal y una pizca de azúcar y dejar hervir hasta que espese.",
            "Retirar del fuego o bajar la llama y agregar la crema fresca.",
            "Rellenar las tortillas con el pollo y el queso de capas desmenuzados. Enrollar y colocar en un pyrex.",
            "Bañar con el resto de la salsa verde, espolvorear con el queso parmesano y gratinar en el horno.",
            "Decorar con cilantro picado antes de servir.",
        ],
        "teacher_notes": [
            "Chilaquiles: cortar las tortillas en cuatro, freírlas como totopos, bañarlas con la salsa verde caliente y servir con huevos revueltos o estrellados encima.",
        ],
        "notes": [],
    },
    "287#1": {
        "refs": ["287#1"],
        "title": "Enchiladas suizas con tomate verde",
        "category": "Platos principales",
        "tags": ["pollo", "horneado"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [
            {"name": "Salsa verde", "items": [
                "6 a 8 miltomates",
                "4 tomates verdes",
                "1 cebolla",
                "1 diente de ajo",
                "2 cucharadas de crema agria",
                "1 cucharada de cilantro picado",
            ]},
            {"name": "Relleno y gratinado", "items": [
                "Tortillas de maíz",
                "Pollo para rellenar",
                "Queso Oaxaca o mozzarella",
            ]},
        ],
        "steps": [
            "Cocer los miltomates y tomates verdes con la cebolla y el ajo.",
            "Licuar con la crema agria y el cilantro picado.",
            "Rellenar las tortillas con pollo, bañar con la salsa verde y cubrir con queso Oaxaca o mozzarella.",
            "Gratinar en el horno hasta dorar el queso.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "209#2": {
        "refs": ["209#2"],
        "title": "Turrón",
        "category": "Básicos y rellenos",
        "tags": ["sin horno"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "2 tazas de azúcar",
            "1 taza de agua",
            "1/4 taza de miel blanca",
            "3 claras de huevo",
            "Jugo de limón",
        ]}],
        "steps": [
            "Mezclar el azúcar con el agua y la miel y poner al fuego sin mover hasta que dé punto de hebra floja.",
            "Batir las claras a punto de nieve e ir agregando la miel caliente poco a poco.",
            "Agregar el jugo de limón y batir hasta que dé punto firme.",
        ],
        "teacher_notes": ["La miel no se mueve: solo se colocan los ingredientes."],
        "notes": ["Instituto Femenino de Estudios Superiores, Hogar Empresa I, Técnicas Culinarias, Sra. Beatriz de Arzú."],
    },
    "276#1": {
        "refs": ["276#1"],
        "title": "Turrón con polvo de clara",
        "category": "Básicos y rellenos",
        "tags": ["sin horno"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "1 taza de azúcar",
            "1/4 taza de agua para punto de hebra (o 3/4 taza de agua)",
            "1/2 onza de polvo de clara (merengue)",
        ]}],
        "steps": [
            "Poner el azúcar con el agua al fuego para hacer una miel a punto de hebra o bola suave.",
            "Batir el polvo de clara a velocidad alta hasta que forme picos firmes.",
            "Bajar la velocidad e incorporar la miel caliente en hilo continuo, batiendo hasta que tenga brillo y firmeza.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "274#2": {
        "refs": ["274#2"],
        "title": "Arroz cocido",
        "category": "Platos principales",
        "tags": ["vegetariano"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "Arroz corriente",
            "Agua o caldo",
            "Aceite o mantequilla",
            "Sal al gusto",
        ]}],
        "steps": [
            "Lavar y sofreír el arroz con un poco de grasa.",
            "Agregar el doble de líquido y sal.",
            "Tapar y cocinar a fuego bajo hasta que seque y esponje.",
        ],
        "teacher_notes": [],
        "notes": ["La receta original no indica cantidades."],
    },
    "285#1": {
        "refs": ["285#1"],
        "title": "Arroz cocido con verduras",
        "category": "Platos principales",
        "tags": ["vegetariano"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "Arroz corriente",
            "Cebolla",
            "Tomate",
            "2 miltomates",
            "Chile pimiento",
            "Clavo",
            "Pimienta",
            "Zanahoria",
            "Papa",
        ]}],
        "steps": [
            "Sofreír el arroz con la cebolla, el tomate, los miltomates y el chile pimiento.",
            "Agregar agua, clavo, pimienta, y la zanahoria y la papa cortadas en cubitos.",
            "Cocinar tapado a fuego bajo hasta que el grano esté cocido y el líquido se consuma.",
        ],
        "teacher_notes": [],
        "notes": ["La receta original no indica cantidades."],
    },
}

for cluster_id, fix in FIXES.items():
    refs = fix.pop("refs")
    path = RECIPES / f"{cluster_id.replace('#', '_')}.json"
    data = {"cluster": cluster_id, "kind": "recipe", "source_refs": refs, "source_hash": "manual", "recipe": fix}
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{path.name}: {fix['title']}")
