"""Rewrite the batch 25 recipes (pages 172-185) from their page extractions.

The earlier hand-written versions had invented ingredients, steps, times and temperatures
that don't match the scans. These stick to what cache/pages/ says.
"""

import json
from pathlib import Path

RECIPES = Path("cache/recipes")

FIXES = {
    "172#1": {
        "refs": ["172#1"],
        "title": "Frijoles pizza",
        "category": "Platos principales",
        "tags": ["horneado", "carne"],
        "servings": "",
        "prep_time": "",
        "cook_time": "1 h 25 min",
        "temperature": "375 °F",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "1 libra de frijol blanco remojado toda la noche y escurrido",
            "1 libra de carne molida",
            "4 cebollas extranjeras, peladas y picadas",
            "1 taza de salsa de tomate para espagueti",
            "1/2 libra de pepperoni o jamón rodajado",
            "1 taza de queso suizo rallado (o Kraft)",
            "2 cucharaditas de orégano",
        ]}],
        "steps": [
            "Cocinar los frijoles en 2 litros de agua hasta que estén suaves, aproximadamente 1 hora. Escurrir y colocarlos en una cacerola o pyrex.",
            "En un sartén dorar a fuego alto la carne con la cebolla y escurrir la grasa.",
            "Añadir la carne y cebolla a los frijoles junto con la salsa de espagueti y el pepperoni o el jamón.",
            "Colocar encima el queso rallado y el orégano.",
            "Hornear a 375 °F por 25 minutos o hasta que esté caliente y un poco dorado.",
        ],
        "teacher_notes": ["Anotación a mano: usar queso suizo rallado y dorar la carne a fuego alto."],
        "notes": [],
    },
    "172#2": {
        "refs": ["172#2"],
        "title": "Omelette al horno",
        "category": "Platos principales",
        "tags": ["horneado", "desayuno", "vegetariano"],
        "servings": "",
        "prep_time": "",
        "cook_time": "40 a 45 min",
        "temperature": "325 °F",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "1/4 taza de mantequilla o margarina",
            "1 taza de crema agria",
            "2 cucharaditas de sal",
            "2 tazas de queso cheddar o Kraft rallado (8 onzas)",
            "4 cebollas tiernas rodajadas (o 1/4 taza de cebollín)",
            "18 huevos",
            "1 taza de leche",
            "1/4 cucharadita de albahaca",
            "1 latita de 4 onzas de hongos en pedazos, escurridos",
            "1 lata de chile pimiento picado y escurrido",
        ]}],
        "steps": [
            "En un molde refractario de 13x9x2, calentar la margarina en el horno a 325 °F hasta que se derrita. Hacer que cubra el molde.",
            "Batir los huevos, crema agria, leche, sal y albahaca en un recipiente grande hasta que estén bien mezclados.",
            "Agregar el queso, chile pimiento, hongos y cebolla, y colocar en el molde.",
            "Cocinar destapado hasta que esté firme pero húmedo, 40 a 45 minutos.",
            "Se puede cortar en cuadros.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "173#1": {
        "refs": ["173#1"],
        "title": "Pasta al pesto",
        "category": "Platos principales",
        "tags": ["rápido", "vegetariano"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [
            {"name": "Pasta", "items": [
                "1 libra de pasta cocida al dente",
                "Mantequilla para freír",
                "Queso parmesano para rociar",
            ]},
            {"name": "Pesto", "items": [
                "2 tazas de hojas de albahaca fresca",
                "1 taza de aceite de oliva",
                "1 taza de leche",
                "2 cucharaditas de sal",
                "Pimienta al gusto",
                "6 dientes de ajo grandes",
                "1 1/4 taza de queso parmesano",
                "4 cucharadas de agua (opcional)",
                "1/3 taza de piñones o nuez de marañón tostada",
            ]},
        ],
        "steps": [
            "Licuar los ingredientes del pesto, excepto la nuez.",
            "Agregar la nuez y volver a licuar.",
            "Freír el pesto en mantequilla y agregarlo a la pasta cocida.",
            "Rociar con más queso parmesano.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "173#2": {
        "refs": ["173#2"],
        "title": "Ratatouille",
        "category": "Platos principales",
        "tags": ["vegetariano", "guiso"],
        "servings": "",
        "prep_time": "",
        "cook_time": "15 a 20 min",
        "temperature": "",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "1/2 taza de aceite de oliva normal o extra virgen",
            "2 dientes de ajo bien picaditos",
            "1 berenjena cortada en cubos (con cáscara)",
            "1 cebolla grande cortada en cubos o en gajos",
            "1 a 2 chiles pimientos cortados en cubos (rojos o verdes)",
            "2 tomates manzanos sin pepitas cortados en cubos",
            "2 güicoyitos partidos en cubos",
            "1/2 taza de champiñones cortados en tajadas",
            "Sal, orégano, azúcar, pimienta y albahaca seca",
            "1/4 a 1/2 taza de agua",
        ]}],
        "steps": [
            "En un sartén freír el aceite con el ajo, orégano seco, albahaca seca, berenjena, cebolla y chile pimiento, alrededor de 3 minutos.",
            "Agregar los champiñones y güicoyitos. Sazonar y agregar 1/4 a 1/2 taza de agua.",
            "Después de 10 minutos agregar el tomate.",
            "Servir caliente o frío, solo o dentro de tomates o mitades de chiles pimientos.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "174#1": {
        "refs": ["174#1", "175#1"],
        "title": "Arroz frito",
        "category": "Platos principales",
        "tags": ["frito", "carne", "pescado y mariscos"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [
            {"name": "Arroz", "items": [
                "1 libra de arroz Gallo Dorado",
                "3 a 4 tazas de agua a punto de hervir",
                "1 1/2 cucharaditas de sal",
            ]},
            {"name": "Salteado", "items": [
                "6 rodajas de tocino picado",
                "Aceite vegetal",
                "3/4 libra de posta de marrano (o lomito) cortada en tiras delgadas, preparada en salmuera",
                "1/2 libra de camarones desvenados y picados gruesos",
                "Cebolla o tallo de cebolla picada fina (o cebollín)",
                "Jengibre fresco (si hubiera)",
                "1 a 2 cucharadas de salsa de soya",
                "3 huevos revueltos hechos tortilla y rodajeados",
                "Saborín al gusto",
            ]},
            {"name": "Salmuera para la carne", "items": [
                "2 a 3 cucharadas de salsa de soya",
                "1/2 cucharada de azúcar morena",
                "1/2 cucharada de miel",
                "Canela en polvo",
                "2 ajos picaditos",
                "Cebollín picadito",
                "1 cucharada de vino tinto (sirve también para lomo o pollo)",
            ]},
        ],
        "steps": [
            "Poner la posta de marrano en la salmuera por lo menos una hora antes. Luego hornearla 20 minutos a 350 °F y rodajearla.",
            "Unir el agua y la sal en una olla, tapar y dejar que llegue a punto de ebullición. Añadir el arroz y revolver. Bajar a fuego lento hasta que el arroz se vea tierno y estilar.",
            "Freír el tocino en wok o sartén grande a fuego medio, revolviendo hasta que esté crujiente; estilar.",
            "Sacar la grasa dejando únicamente 1 cucharada y en ella hacer los huevos en forma de tortilla. Enrollarlos y cortarlos en tiras delgadas.",
            "Agregar aceite y cebollín, luego jengibre (si hubiera fresco), cebolla o tallo de cebolla, camarones, arroz, tiras de tortilla, tocino, carne de cerdo cocinada y salsa de soya.",
            "Cocinar y revolver hasta que quede bien caliente.",
        ],
        "teacher_notes": ["Anotación a mano: se puede hacer con lomito, lomo o pollo."],
        "notes": [],
    },
    "175#2": {
        "refs": ["175#2"],
        "title": "Pechugas de pollo estilo chino con marañón",
        "category": "Platos principales",
        "tags": ["pollo", "guiso"],
        "servings": "6",
        "prep_time": "",
        "cook_time": "30 min",
        "temperature": "",
        "ingredient_groups": [
            {"name": "Pollo", "items": [
                "6 pechugas de pollo con hueso, sin piel",
                "2 onzas de mantequilla",
                "4 onzas de tocino picadito",
                "2 cucharadas de mostaza",
                "1/4 taza de salsa inglesa",
                "Laurel",
                "1 taza de agua",
            ]},
            {"name": "Salsa", "items": [
                "1/2 taza de salsa de soya",
                "Jugo de la piña con 1 cucharada de maicena",
                "1 lata de piña en trocitos",
                "1/4 libra de jamón picadito",
                "1 taza de hongos frescos rodajeados (shiitake)",
                "Consomé de pollo al gusto",
                "Azúcar, pimienta y tabasco al gusto",
                "Semilla de marañón tostada",
            ]},
        ],
        "steps": [
            "Freír el tocino, agregar la mantequilla y dorar el pollo.",
            "Agregar la salsa inglesa, laurel, mostaza y 1 taza de agua. Tapar la olla y dejar cocer 20 a 30 minutos. Apartar el caldo.",
            "Para la salsa, unir el jugo de la piña con la maicena, salsa de soya y azúcar (y caldo de pollo si fuera necesario).",
            "Poner a hervir y agregar la piña, el jamón y los hongos. Dejar hervir.",
            "Verificar la sazón, agregar sobre el pollo y adornar con nuez de marañón.",
            "Se puede servir con verduras salteadas en sartén o wok.",
        ],
        "teacher_notes": [
            "Técnica en sartén (anotada a mano): 1) Freír en sartén tocino, champiñones, jamón, mostaza y salsa de soya. 2) Agregar el pollo ya dorado en mantequilla, luego el consomé y el jugo de piña, y sazonar. Por último la piña y la nuez de marañón.",
        ],
        "notes": [],
    },
    "176#1": {
        "refs": ["176#1"],
        "title": "Champiñones rellenos",
        "category": "Entradas y bocadillos",
        "tags": ["horneado", "festivo"],
        "servings": "24 piezas",
        "prep_time": "",
        "cook_time": "8 min",
        "temperature": "",
        "ingredient_groups": [
            {"name": "Relleno y base", "items": [
                "24 cabezas de hongos (sin tallo)",
                "1 taza de pan cortado en cubos",
                "1/4 taza de jamón finamente picado",
                "2 cucharadas de perejil picadito",
                "2 cucharadas de margarina o mantequilla",
                "Pan blanco de rodaja cortado en 24 redondeles",
                "Perejil colocho para decorar",
            ]},
            {"name": "Topping de queso", "items": [
                "1 cucharada de vino blanco",
                "3/4 taza de queso cheddar rallado (u otro)",
                "1/4 cucharadita de sal",
                "1 cucharada de salsa inglesa",
                "Mostaza en polvo al gusto",
                "Pimienta al gusto",
            ]},
        ],
        "steps": [
            "Cortar 24 redondeles de pan y apartar.",
            "Para el relleno, poner en una ollita el pan en cubos, jamón, mantequilla y perejil, y revolver. Verificar la sazón y rellenar los hongos.",
            "Colocar los hongos sobre los redondeles de pan untados con mantequilla y hornear 5 minutos.",
            "Para el topping, calentar el vino, unirlo al queso para que se derrita, agregar los sazonadores y batir bien.",
            "Poner la mezcla por cucharaditas sobre los hongos y volver a hornear 3 minutos más.",
            "Decorar con perejil colocho.",
        ],
        "teacher_notes": ["Las rueditas de pan ya las venden hechas; se brochan con mantequilla."],
        "notes": [],
    },
    "177#1": {
        "refs": ["177#1"],
        "title": "Quiches de fiesta",
        "category": "Entradas y bocadillos",
        "tags": ["horneado", "festivo"],
        "servings": "",
        "prep_time": "",
        "cook_time": "8 min",
        "temperature": "",
        "ingredient_groups": [
            {"name": "Base", "items": ["1/2 masa de pie"]},
            {"name": "Rellenos variados", "items": [
                "3 cucharadas de chile pimiento rojo picadito",
                "3 cucharadas de champiñones picaditos",
                "3 cucharadas de tocino picadito frito",
                "3 cucharadas de hierbas frescas (perejil, cilantro, albahaca)",
                "3 cucharadas de queso rallado (suizo o pecorino)",
            ]},
            {"name": "Mezcla de huevo", "items": [
                "1 huevo",
                "2 cucharadas de leche y crema",
                "1/4 cucharadita de sal",
                "1/4 cucharadita de pimienta",
                "1/4 cucharadita de mostaza en polvo",
            ]},
        ],
        "steps": [
            "Hacer las costras con la masa de pie y dejarlas crudas.",
            "Rellenar unas de chile pimiento, otras de champiñones, de hierbas y de tocino.",
            "Rociar con un poquito de queso rallado.",
            "Colocarles con cuchara la mezcla de huevo con leche, crema y sazonadores.",
            "Hornear por 8 minutos.",
        ],
        "teacher_notes": ["La mezcla líquida se va echando con cuchara."],
        "notes": [],
    },
    "177#2": {
        "refs": ["177#2", "178#1"],
        "title": "Tostaditas de sabores",
        "category": "Entradas y bocadillos",
        "tags": ["horneado", "festivo"],
        "servings": "",
        "prep_time": "",
        "cook_time": "8 min",
        "temperature": "400 °F",
        "ingredient_groups": [
            {"name": "Masa", "items": [
                "2 1/4 tazas de harina cernida",
                "1/2 cucharadita de sal",
                "1/2 cucharadita de pimienta de cayena",
                "1 cucharadita de mostaza en polvo",
                "3/4 taza de mantequilla (6 onzas)",
                "1 taza de queso cheddar rallado",
                "1 huevo batido",
            ]},
            {"name": "Sabores", "items": [
                "2 cucharadas de ajonjolí",
                "2 cucharadas de semillas de amapola (poppy seeds)",
                "2 cucharadas de pasta de tomate",
            ]},
        ],
        "steps": [
            "Hacer la masa con los primeros ingredientes, como masa de pie. Dividirla en tres.",
            "A una parte colocarle ajonjolí y formar un tubo.",
            "A otra colocarle poppy seeds y formar un tubo.",
            "Extender la última, colocarle la pasta de tomate y enrollarla, quedando también en forma de tubo.",
            "Refrigerar hasta que agarre firmeza.",
            "Cortar en rodajas y colocar en latas engrasadas y enharinadas. Hornear a 400 °F por 8 minutos, hasta que salgan doraditas.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "178#2": {
        "refs": ["178#2"],
        "title": "Pastelitos de zucchini",
        "category": "Entradas y bocadillos",
        "tags": ["horneado", "vegetariano"],
        "servings": "",
        "prep_time": "",
        "cook_time": "10 a 15 min",
        "temperature": "400 °F",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "3 zucchinis medianos rallados",
            "2 cucharaditas de sal",
            "6 cucharaditas de aceite de oliva",
            "1 cebolla mediana picada",
            "1 taza de harina",
            "1 cucharadita de polvo de hornear",
            "5 huevos",
            "2 cucharadas de leche",
            "1 1/2 tazas de queso parmesano",
            "1 diente de ajo picado",
            "2 cucharadas de albahaca fresca",
            "1/4 cucharadita de pimienta",
        ]}],
        "steps": [
            "Sacarle el exceso de agua al zucchini dejándolo con la sal; escurrir bien.",
            "Calentar el aceite y freír la cebolla y el zucchini.",
            "Aparte unir los ingredientes secos, y aparte los líquidos. Unir ambos y verter la mezcla de cebolla y zucchini.",
            "Colocar en moldes individuales o en pyrex engrasado y enharinado.",
            "Hornear de 10 a 15 minutos a 400 °F.",
            "Cortar y servir en cápsulas.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "179#1": {
        "refs": ["179#1"],
        "title": "Egg nog",
        "category": "Bebidas",
        "tags": ["festivo", "sin horno"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "3 huevos separados",
            "1/2 taza de azúcar glass (o hasta 1 taza, al gusto)",
            "1/2 taza de cognac o brandy",
            "1/2 taza de ron",
            "1 1/2 tazas de leche fría",
            "1 taza de crema líquida",
            "1 cucharadita de vainilla o café (opcional)",
            "Canela en polvo",
            "Nuez moscada para espolvorear",
            "Hielo",
        ]}],
        "steps": [
            "Batir las yemas con el azúcar glass hasta que espesen.",
            "Agregar el cognac, ron, canela, leche y crema (o licuar todo junto). Mezclar bien.",
            "Poner a enfriar.",
            "Un momento antes de servir, colocarle hielo.",
            "Batir las claras a punto de nieve y agregarlas sin moverlas mucho.",
            "Espolvorear con nuez moscada.",
        ],
        "teacher_notes": [
            "El azúcar glass puede ir de 1/2 a 1 taza, según lo dulce que lo quieran.",
            "La mezcla de yemas y licores se puede licuar.",
        ],
        "notes": [],
    },
    "180#1": {
        "refs": ["180#1"],
        "title": "Choux de cangrejo",
        "category": "Entradas y bocadillos",
        "tags": ["horneado", "festivo", "pescado y mariscos"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [
            {"name": "Choux", "items": [
                "1 receta de masa choux (receta de Beatriz de Arzú)",
                "1 huevo batido o mantequilla para barnizar",
                "2 cucharaditas de ajonjolí",
            ]},
            {"name": "Sofrito", "items": [
                "1 cucharada de mantequilla",
                "2 cucharadas de cebollín picado",
                "2 cucharadas de hierbas frescas (perejil, albahaca, orégano y cilantro)",
            ]},
            {"name": "Relleno de cangrejo", "items": [
                "1 taza de cangrejo desmenuzado con tenedor",
                "1/2 taza de crema",
                "1 cucharada de mayonesa",
                "Sal y pimienta al gusto",
            ]},
        ],
        "steps": [
            "Hacer los choux y, a medio cocinar, brochearlos y agregarles ajonjolí.",
            "Para el relleno, freír en la mantequilla el cebollín y las hierbas.",
            "Agregar este sofrito a la mezcla de cangrejo, crema y mayonesa. Revolver bien y sazonar.",
            "Rellenar los choux.",
        ],
        "teacher_notes": [
            "También se pueden rellenar panitos botaneros: se aplastan panitos con bolillo, se cortan en rueditas con cortadores de galleta, se colocan en lámina de cubiletes sin engrasar, se hornean hasta dorar y luego se rellenan.",
        ],
        "notes": [],
    },
    "181#1": {
        "refs": ["181#1"],
        "title": "Jamón Virginia horneado con salsa especial",
        "category": "Platos principales",
        "tags": ["horneado", "festivo", "carne"],
        "servings": "",
        "prep_time": "",
        "cook_time": "1 h",
        "temperature": "350 °F",
        "ingredient_groups": [
            {"name": "Jamón y glaseado", "items": [
                "1 trozo de jamón Virginia",
                "Clavos de olor",
                "2/3 taza de miel de maple",
                "1/3 taza de azúcar morena",
                "Clavo, canela y jengibre en polvo al gusto",
                "Jugo de 1 naranja",
            ]},
            {"name": "Acompañamiento (opcional)", "items": [
                "Manzanas cortadas en rodajas",
                "Mantequilla",
            ]},
            {"name": "Salsa agridulce", "items": [
                "1/4 taza de salsa de soya",
                "1/4 taza de vinagre oscuro",
                "1 cucharada de mostaza",
                "1 cucharada de maicena",
                "1/4 taza de azúcar morena",
                "2 tazas de jugo de piña",
            ]},
        ],
        "steps": [
            "Insertar los clavos de olor en el jamón. Con el resto de los ingredientes del glaseado hacer una salsa y bañar el jamón.",
            "Hornear a 350 °F por 1 hora, mojando el jamón de vez en cuando.",
            "Si se desea, freír las manzanas en la mantequilla hasta suavizar y servirlas de acompañamiento.",
            "Para la salsa agridulce, deshacer la maicena en el jugo de piña, agregar el resto de ingredientes y poner a espesar.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
    "182#1": {
        "refs": ["182#1"],
        "title": "Arroz al horno navideño",
        "category": "Platos principales",
        "tags": ["horneado", "festivo"],
        "servings": "",
        "prep_time": "",
        "cook_time": "25 min",
        "temperature": "350 °F",
        "ingredient_groups": [{"name": "Ingredientes", "items": [
            "Arroz",
            "Mantequilla",
            "Cebolla picada",
            "Ajo picado",
            "Caldo de pollo o res",
            "Arvejas tiernas",
            "Pasas",
            "Chile pimiento picado",
        ]}],
        "steps": [
            "Sofreír en la mantequilla la cebolla y el ajo, y agregar el arroz.",
            "Agregar el resto de ingredientes, excepto el caldo, las arvejas, las pasas y el chile pimiento. Mezclar bien.",
            "Agregar el caldo y luego lo restante.",
            "Tapar y hornear por 25 minutos a 350 °F.",
        ],
        "teacher_notes": [],
        "notes": ["La receta original no indica cantidades.", "Acompañamiento para el jamón Virginia horneado."],
    },
    "183#1": {
        "refs": ["183#1", "190#1"],
        "title": "Lomo de cerdo con salsa de ciruelas",
        "category": "Platos principales",
        "tags": ["carne", "horneado", "festivo"],
        "servings": "",
        "prep_time": "",
        "cook_time": "",
        "temperature": "",
        "ingredient_groups": [
            {"name": "Carne", "items": [
                "1 lomo de cinta",
                "Mantequilla o aceite",
                "Sal, pimienta y ajo machacado",
                "1 cucharada de cebolla picada",
                "2 cucharadas de zanahoria en cuadritos",
            ]},
            {"name": "Salsa", "items": [
                "15 ciruelas despepitadas",
                "1/4 botella de vino tinto",
                "Consomé de res espeso",
                "1 taza de crema",
                "1 a 2 cucharadas de harina",
                "Perejil picado",
            ]},
        ],
        "steps": [
            "Aparte, poner las ciruelas en el vino a fuego lento.",
            "Sobar el lomo con sal, pimienta y ajo machacado. Dorarlo en el aceite o mantequilla y rodajearlo.",
            "Agregar la cebolla y la zanahoria, luego el consomé de res, y dejar reducir.",
            "Agregar la crema y la harina, y por último la mezcla de ciruelas y vino.",
            "Se puede meter al horno después de tenerlo acabado con la salsa.",
        ],
        "teacher_notes": [
            "Se puede hacer con chuletas.",
            "En lugar de la crema se puede usar una salsa blanca: 1 onza de margarina, 3 o 4 cucharadas de harina doradas, 1/2 taza de leche y 1 taza de leche evaporada.",
        ],
        "notes": [],
    },
    "184#1": {
        "refs": ["184#1", "191#1"],
        "title": "Soufflé de cebolla",
        "category": "Platos principales",
        "tags": ["horneado", "vegetariano"],
        "servings": "8",
        "prep_time": "",
        "cook_time": "30 min",
        "temperature": "350 °F",
        "ingredient_groups": [
            {"name": "Salsa blanca (2 tazas)", "items": [
                "2 cucharadas de mantequilla",
                "3 a 4 cucharadas de harina",
                "1 taza de leche",
                "1 taza de leche evaporada",
                "Sal y pimienta",
            ]},
            {"name": "Soufflé", "items": [
                "3 cebollas partidas en gajos, fritas en poquita mantequilla",
                "1/2 taza de queso cheddar rallado",
                "1 taza de queso pecorino o mozzarella rallado",
                "8 yemas de huevo",
                "8 claras de huevo batidas a punto de nieve",
                "Queso parmesano rallado para rociar",
            ]},
        ],
        "steps": [
            "Precalentar el horno a 350 °F. Engrasar y enharinar un molde (ideal para soufflé).",
            "Hacer la salsa blanca con la mantequilla, harina, leche normal y leche evaporada. Tiene que quedar bien sazonada.",
            "Dejar refrescar. Agregar las yemas medio batidas, las cebollas y los quesos rallados.",
            "Por último, incorporar las claras batidas a punto de nieve en forma envolvente.",
            "Pasar al molde y rociar con queso parmesano.",
            "Hornear a 350 °F por aproximadamente 30 minutos. Consumir inmediatamente.",
        ],
        "teacher_notes": [
            "Porciones por persona: carne 5 a 6 oz, pollo 10 oz, pavo 10 a 12 oz, pierna 10 oz.",
        ],
        "notes": [],
    },
    "185#1": {
        "refs": ["185#1", "192#1"],
        "title": "Pastel de Navidad",
        "category": "Postres y pasteles",
        "tags": ["horneado", "festivo", "frutas"],
        "servings": "12 a 16",
        "prep_time": "40 min",
        "cook_time": "1 h 30 min a 2 h",
        "temperature": "300 °F",
        "ingredient_groups": [
            {"name": "Frutas", "items": [
                "3 1/2 tazas de fruta seca (pasas, fruta cristalizada, albaricoques secos, naranja cristalizada)",
                "1/2 taza de guindas en cuadritos",
                "1/8 taza de ralladura de naranja y limón",
                "1/2 taza de almendra fileteada tostada",
                "Jugo de 1 naranja",
                "1/4 taza de brandy",
            ]},
            {"name": "Masa", "items": [
                "1 1/2 tazas de harina cernida",
                "1/2 cucharada de especias variadas (clavo, jengibre, canela, nuez moscada)",
                "1 1/4 tazas de azúcar morena",
                "1 1/4 tazas de mantequilla suavizada",
                "1 cucharada de miel de caña o miel Karo oscura",
                "1/2 taza de almendras trituradas",
                "3 huevos batidos",
            ]},
            {"name": "Decoración", "items": [
                "Mazapán o fondant",
                "Colorantes",
                "Jalea de albaricoque",
            ]},
        ],
        "steps": [
            "Precalentar el horno a 300 °F. Engrasar y enharinar un molde redondo desmoldable y forrarlo con papel encerado.",
            "En un bowl combinar muy bien la fruta seca con las guindas, la ralladura y las almendras. Agregar el jugo de naranja y el brandy y combinar bien.",
            "En otro bowl combinar la harina, especias, azúcar morena, mantequilla, miel, almendra triturada y huevos. Batir suavemente hasta que quede bien unido.",
            "Unir las dos mezclas, colocar en el molde y presionar.",
            "Hornear de 1 1/2 a 2 horas a 300 °F.",
            "Decorar con mazapán o fondant, colorantes y jalea de albaricoque.",
        ],
        "teacher_notes": [],
        "notes": [],
    },
}

for cluster_id, fix in FIXES.items():
    refs = fix.pop("refs")
    path = RECIPES / f"{cluster_id.replace('#', '_')}.json"
    data = {"cluster": cluster_id, "kind": "recipe", "source_refs": refs, "source_hash": "manual", "recipe": fix}
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{path.name}: {fix['title']}")
